<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InvitemyTeam</name>
   <tag></tag>
   <elementGuidId>6936429e-936a-4696-b187-0b0560d9faaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div/div/div/ul/li[2]/label/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
